#!/bin/bash

# shellcheck source=/dev/null
source ./src/help # Show help message
source ./src/sub # Get sub from user (get_subreddit)
source ./src/version # Show version
source ./src/scrap # Scrap images from subreddit

# args
while [ $# -gt 0 ]; do
	case $1 in
		-h|--help)
			help_info
			exit 0
			;;
		-l|--limit)
			shift
			LIMIT=$1
			case $LIMIT in
				''|*[!0-9]*)
					echo 'limit is NaN'
					exit 1
			esac
			shift
			;;
		-v|--version)
			version
			exit 0
			;;
		*)
			subreddit=$1
			shift
			;;
	esac
done

# Default config directory
configdir="${XDG_CONFIG_HOME:-$HOME/.config}/redyt"

# Create .config/redyt if it does not exist to prevent
# the program from not functioning properly
[ ! -d "$configdir" ] && echo "Directory $configdir does not exist, creating..." && mkdir -p "$configdir"

# If subreddit.txt does not exist, create it to prevent
# the program from not functioning properly
[ ! -f "$configdir/subreddit.txt" ] && echo "File $configdir/subreddit.txt does not exist, creating..." && touch "$configdir/subreddit.txt"

# If no argument is passed
get_subreddit

# Default directory used to store the feed file and fetched images
cachedir="./images"

# If cachedir does not exist, create it
if [ ! -d "$cachedir" ]; then
	echo "Directory $cachedir does not exist, creating..."
	mkdir -p "$cachedir"
fi

scrap "$subreddit" "$cachedir"

# Once finished, remove all of the cached images
#[[ "$KEEP" != "1" ]] && rm "${cachedir:?}"/*