#!/bin/bash

# shellcheck source=/dev/null
source ./src/help # Show help message
source ./src/sub # Get sub from user (get_subreddit)
source ./src/version # Show version
source ./src/scrap # Scrap images from subreddit
source ./src/cache # Cache images
source ./src/dir # Get directory from user (get_dir)

# args
while [ $# -gt 0 ]; do
	case $1 in
		-h|--help)
			help_info
			exit 0
			;;
		-l|--limit)
			shift
			LIMIT=$1
			case $LIMIT in
				''|*[!0-9]*)
					echo 'limit is NaN'
					exit 1
			esac
			shift
			;;
		-v|--version)
			version
			exit 0
			;;
		*)
			subreddit=$1
			shift
			;;
	esac
done

get_dir

# If no argument is passed
get_subreddit

cache

${cachedir:?}

scrap "$subreddit" "$cachedir"

# Once finished, remove all of the cached images
#[[ "$KEEP" != "1" ]] && rm "${cachedir:?}"/*