#!/bin/bash

args() {
    # args
    while [ $# -gt 0 ]; do
        case $1 in
            -h|--help)
                help_info
                exit 0
                ;;
            -l|--limit)
                shift
                LIMIT=$1
                case $LIMIT in
                    ''|*[!0-9]*)
                        echo 'limit is NaN'
                        exit 1
                esac
                shift
                ;;
            -v|--version)
                version
                exit 0
                ;;
            *)
                subreddit=$1
                echo "subreddit: $subreddit"
                shift
                ;;
        esac
    done
}
